FROM ubuntu:24.04

# Create user and home directory
RUN useradd -ms /bin/bash grc-iit

# Install all required packages
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
      git g++ python3 curl build-essential unzip tar \
      libtool pkg-config jq lsof cmake locales

# Set up locale (UTF-8)
RUN locale-gen en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

# Switch to user, home and working directory
USER grc-iit
WORKDIR /home/grc-iit

# Install Spack in user home
RUN git clone --branch v0.21.2 https://github.com/spack/spack.git /home/grc-iit/Spack && \
    echo "source /home/grc-iit/Spack/spack/share/spack/setup-env.sh" >> /home/grc-iit/.bashrc

# Set SPACK_ROOT and PATH (for both shell and scripts)
ENV SPACK_ROOT=/home/grc-iit/Spack/spack
ENV PATH=$SPACK_ROOT/bin:$PATH

# Use bash for all shell commands
SHELL ["/bin/bash", "-c"]

# Main project workdir, to be mounted by CI/CD
WORKDIR /workspace