name: Build AMD64 Image (Temporary Debug)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag to build'
        required: true
        default: 'v1.0.0'
        type: string
      base_image_tag:
        description: 'Base image tag to use'
        required: false
        default: 'latest'
        type: string

jobs:
  build-amd64-temp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set environment variables
        run: |
          echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV
          echo "GHCR_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Build & Push AMD64 image
        uses: docker/build-push-action@v5
        timeout-minutes: 60
        with:
          context: .
          file: .github/docker/Dockerfile.chronolog
          platforms: linux/amd64
          push: true
          no-cache: true
          build-args: |
            VERSION=${{ env.VERSION }}
            BASE_IMAGE=ghcr.io/${{ env.GHCR_OWNER }}/chronolog-base:latest
          tags: |
            ghcr.io/${{ env.GHCR_OWNER }}/chronolog:${{ env.VERSION }}-amd64
            ghcr.io/${{ env.GHCR_OWNER }}/chronolog:latest
