name: Build ARM64 Image

on:
  release:
    types: [published]

jobs:
  build-arm64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag and normalize owner
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "GHCR_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Build & Push ARM64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: CI/docker/local.dockerfile
          platforms: linux/arm64
          push: true
          build-args: VERSION=${{ env.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/${{ env.GHCR_OWNER }}/chronolog:${{ env.VERSION }}-arm64