name: Build AMD64 Image

on:
  workflow_dispatch: 
  workflow_run:
    workflows: ["Build ChronoLog Base AMD64 Image"]
    types:
      - completed

jobs:
  build-amd64:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Increase timeout to 30 minutes
    
    # Request more resources
    env:
      DOCKER_BUILDKIT_MEMORY: 4g
      DOCKER_BUILDKIT_SWAP: 2g

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from base image tag
        run: |
          echo "VERSION=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_ENV
          echo "GHCR_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Debug GitHub Actions Environment
        run: |
          echo "=== GitHub Actions Environment Debug ==="
          echo "Runner OS: $RUNNER_OS"
          echo "Runner Architecture: $RUNNER_ARCH"
          echo "Workflow: $GITHUB_WORKFLOW"
          echo "Run ID: $GITHUB_RUN_ID"
          echo "Run Number: $GITHUB_RUN_NUMBER"
          echo "Job: $GITHUB_JOB"
          echo "=== System Resources ==="
          echo "CPU Info:"
          nproc
          cat /proc/cpuinfo | grep "model name" | head -1
          echo "Memory Info:"
          free -h
          echo "Disk Info:"
          df -h
          echo "Docker Info:"
          docker version
          docker system df
          echo "=== Build Start Time: $(date) ==="

      - name: Monitor Resources (Background)
        run: |
          # Start resource monitoring in background
          (
            while true; do
              echo "=== $(date): Resource Monitor ==="
              echo "Memory: $(free -h | grep Mem)"
              echo "CPU Load: $(uptime)"
              echo "Disk: $(df -h / | tail -1)"
              sleep 30
            done
          ) &
          echo "Resource monitoring started with PID: $!"
          echo "MONITOR_PID=$!" >> $GITHUB_ENV

      - name: Build & Push AMD64 image
        uses: docker/build-push-action@v5
        timeout-minutes: 60
        with:
          context: .
          file: .github/docker/Dockerfile.chronolog
          platforms: linux/amd64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ env.VERSION }}
            BASE_IMAGE=ghcr.io/${{ env.GHCR_OWNER }}/chronolog-base:latest
          tags: ghcr.io/${{ env.GHCR_OWNER }}/chronolog:${{ env.VERSION }}-amd64

      - name: Post-build Debug Info
        if: always()
        run: |
          echo "=== Build End Time: $(date) ==="
          echo "=== Final System Resources ==="
          free -h
          df -h
          docker system df
          echo "=== Docker processes ==="
          docker ps -a