# .github/workflows/build-base.yml
name: Build ChronoLog Base Image

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "GHCR_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Build & Push base image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .github/docker/Dockerfile.base
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/${{ env.GHCR_OWNER }}/chronolog-base:${{ env.VERSION }}
            ghcr.io/${{ env.GHCR_OWNER }}/chronolog-base:latest