name: Build ARM64 Image

on:
  workflow_run:
    workflows: ["Build ChronoLog Base Image"]
    types:
      - completed

jobs:
  build-arm64:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from base image tag
        run: |
          echo "VERSION=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_ENV
          echo "GHCR_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Build & Push ARM64 image
        uses: docker/build-push-action@v5
        timeout-minutes: 60
        with:
          context: .
          file: .github/docker/Dockerfile.chronolog
          platforms: linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ env.VERSION }}
            BASE_IMAGE=ghcr.io/${{ env.GHCR_OWNER }}/chronolog-base:latest
          tags: |
            ghcr.io/${{ env.GHCR_OWNER }}/chronolog:${{ env.VERSION }}-amd64