name: ChronoLog CI Build, Install, and Deploy

on:
  pull_request:
    branches: [ develop ]

jobs:
  ci-check:
    runs-on: ubuntu-22.04
    timeout-minutes: 90

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t chronolog-ci .github/docker

      - name: Run CI inside Docker container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            chronolog-ci \
            bash -c "
              set -e

              ##################################
              # Step 1: Spack Environment
              ##################################
              echo '[1/6] Setting up Spack...'
              source /opt/spack/share/spack/setup-env.sh
              spack env activate -p .
              spack install

              ##################################
              # Step 2: Build ChronoLog
              ##################################
              echo '[2/6] Building ChronoLog...'
              mkdir -p build
              cd build
              cmake -DCMAKE_BUILD_TYPE=Debug -DINSTALL_DIR=\$HOME/chronolog-install ..
              make -j\$(nproc)

              ##################################
              # Step 3: Install ChronoLog
              ##################################
              echo '[3/6] Installing ChronoLog...'
              make install
              ls -l \$HOME/chronolog-install

              ##################################
              # Step 4: Post-Install Verification
              ##################################
              echo '[4/6] Verifying install...'
              if [ -d \"\$HOME/chronolog-install/Debug/bin\" ]; then
                echo '✅ Install successful!'
                ls -l \$HOME/chronolog-install/Debug/bin
              else
                echo '❌ Install failed — bin directory not found'
                exit 1
              fi

              ##################################
              # Step 5: Deploy ChronoLog
              ##################################
              echo '[5/6] Deploying ChronoLog...'
              cd /workspace/deploy
              ./local_single_user_deploy.sh -d -w \$HOME/chronolog-install/Debug/
              cd ../..

              ##################################
              # Step 6: Check Deployment
              ##################################
              echo '[6/6] Verifying Deployment...'
              sleep 5  # allow time for processes to start

              pgrep -la chrono > /tmp/chrono_processes.txt
              cat /tmp/chrono_processes.txt

              # Initialize status
              missing=0

              for proc in chronovisor_server chrono_grapher chrono_player chrono_keeper; do
                if grep -q "$proc" /tmp/chrono_processes.txt; then
                  echo "✅ Found: $proc"
                else
                  echo "❌ Missing: $proc"
                  missing=1
                fi
              done

              if [ "$missing" -eq 0 ]; then
                echo '✅ All required ChronoLog components are running.'
              else
                echo '❌ One or more ChronoLog components are missing.'
                exit 1
              fi
            "