name: ChronoLog CI Build, Install, and Deploy

on:
  pull_request:
    branches: [ develop ]

jobs:
  ci-check:
    runs-on: ubuntu-22.04
    timeout-minutes: 90

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t chronolog-ci .github/docker

      - name: Run CI inside Docker container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            chronolog-ci \
            bash -c "
              source /opt/spack/share/spack/setup-env.sh &&
              spack env activate -p . &&
              spack install &&
              mkdir -p build &&
              cd build &&
              cmake -DCMAKE_BUILD_TYPE=Debug -DINSTALL_DIR=~/chronolog-install .. &&
              make -j\$(nproc)
            "