name: ChronoLog CI Build, Install, and Deploy

on:
  pull_request:
    branches:
      - develop

jobs:
  ci-check:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y git g++ python3 curl build-essential \
            unzip tar libtool autoconf automake pkg-config jq lsof

      - name: Clone Spack
        run: |
          git clone --branch v0.21.2 https://github.com/spack/spack.git ~/spack
          echo "source ~/spack/share/spack/setup-env.sh" >> ~/.bashrc
          source ~/spack/share/spack/setup-env.sh

      - name: Build ChronoLog
        run: |
          source ~/spack/share/spack/setup-env.sh
          cd deploy
          ./local_single_user_deploy.sh --build --build-type Debug --install-dir /tmp/chronolog-install

      - name: Install ChronoLog
        run: |
          cd deploy
          ./local_single_user_deploy.sh --install --work-dir /tmp/chronolog-install/Debug

      - name: Deploy ChronoLog
        run: |
          cd deploy
          ./local_single_user_deploy.sh --start --work-dir /tmp/chronolog-install/Debug

      - name: Check ChronoLog Processes
        run: |
          sleep 5
          echo "Checking running ChronoLog processes..."
          processes=$(pgrep -laf "chronovisor_server|chrono_grapher|chrono_keeper|chrono_player" || true)

          echo "$processes"

          expected=4
          actual=$(echo "$processes" | grep -cE "chronovisor_server|chrono_grapher|chrono_keeper|chrono_player")

          if [ "$actual" -lt "$expected" ]; then
            echo "❌ Expected $expected ChronoLog processes but found $actual."
            exit 1
          else
            echo "✅ All $expected ChronoLog processes are running."
          fi