name: ChronoLog CI Build, Install, and Deploy

on:
  pull_request:
    branches:
      - develop

jobs:
  ci-check:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: .

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y git g++ python3 curl build-essential \
            unzip tar libtool autoconf automake pkg-config jq lsof

      - name: Clone Spack
        run: |
          git clone --branch v0.21.2 https://github.com/spack/spack.git ~/spack
          echo "source ~/spack/share/spack/setup-env.sh" >> ~/.bashrc
          source ~/spack/share/spack/setup-env.sh

      - name: Activate spack env
        run: |
          source ~/spack/share/spack/setup-env.sh
          spack env activate -p .
          spack install -v

      - name: Build chronolog
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DINSTALL_DIR=/tmp/chronolog-install ..
          cd ..

      - name: Check build dir
        run: |
          cd build
          ls -la